const CATEGORY_SEEDS = [
  { slug: "physics", name: "물리", displayOrder: 1 },
  { slug: "math", name: "수학", displayOrder: 2 },
  { slug: "chemistry", name: "화학", displayOrder: 3 },
  { slug: "biology", name: "생물", displayOrder: 4 },
  { slug: "earth-science", name: "지구과학", displayOrder: 5 },
  { slug: "astronomy", name: "천문학", displayOrder: 6 },
  { slug: "korean", name: "국어", displayOrder: 7 },
  { slug: "hunminjeongeum", name: "훈민정음", displayOrder: 8 },
  { slug: "hanja", name: "한자", displayOrder: 9 },
  { slug: "english", name: "영어", displayOrder: 10 },
  { slug: "philosophy", name: "철학", displayOrder: 11 },
  { slug: "psychology", name: "심리학", displayOrder: 12 },
  { slug: "korean-history", name: "한국사", displayOrder: 13 },
  { slug: "world-history", name: "세계사", displayOrder: 14 },
  { slug: "economics", name: "경제", displayOrder: 15 },
  { slug: "politics", name: "정치", displayOrder: 16 },
  { slug: "law", name: "법학", displayOrder: 17 },
  { slug: "geography", name: "지리", displayOrder: 18 },
  { slug: "algorithm", name: "알고리즘", displayOrder: 19 },
  { slug: "operating-system", name: "운영체제", displayOrder: 20 },
  { slug: "network", name: "네트워크", displayOrder: 21 },
  { slug: "security", name: "보안", displayOrder: 22 },
  { slug: "aws-cloud", name: "AWS/클라우드", displayOrder: 23 },
  { slug: "art", name: "미술", displayOrder: 24 },
  { slug: "music", name: "음악", displayOrder: 25 },
  { slug: "film", name: "영화", displayOrder: 26 },
  { slug: "architecture", name: "건축", displayOrder: 27 },
  { slug: "food", name: "음식", displayOrder: 28 },
  { slug: "sports", name: "스포츠", displayOrder: 29 },
  { slug: "game", name: "게임", displayOrder: 30 },
  { slug: "animals", name: "동물", displayOrder: 31 },
  { slug: "plants", name: "식물", displayOrder: 32 },
];

const DEFAULT_DAILY_WORD = {
  publicTitle: "오늘의 단어",
  hiddenAnswerText: "훈민정음",
  categorySlug: "hunminjeongeum",
  fixedHintText: "세종대왕이 만든 문자 체계와 직접 연결되는 단어야.",
  synonyms: ["훈민정음", "훈민정음언해"],
};

const SAMPLE_PROMPT_ROOMS = [
  {
    categorySlug: "physics",
    titleAsAnswer: "양자얽힘",
    answerType: "word",
    maxInputChars: 120,
    thresholdScore: 82,
    teaserText: "두 입자가 멀리 떨어져 있어도 서로 묶인 듯 움직이는 개념이야.",
    tone: "친한 친구처럼 비웃다가도 좋은 프롬프트엔 바로 흔들리는 고양이 캐릭터",
  },
  {
    categorySlug: "math",
    titleAsAnswer: "이차함수",
    answerType: "word",
    maxInputChars: 100,
    thresholdScore: 80,
    teaserText: "포물선, 축, 꼭짓점 같은 장면으로 유도하면 흔들릴 만한 방이야.",
    tone: "허접한 프롬프트엔 웃고, 정교한 묘사엔 빠르게 흔들리는 고양이 캐릭터",
  },
  {
    categorySlug: "chemistry",
    titleAsAnswer: "황산",
    answerType: "word",
    maxInputChars: 90,
    thresholdScore: 78,
    teaserText: "산성, 부식성, 실험실 분위기로 압박하면 AI가 슬슬 입을 놀릴 수 있어.",
    tone: "사납게 빈정대지만, 과학적 상황극에는 약한 고양이 캐릭터",
  },
  {
    categorySlug: "hunminjeongeum",
    titleAsAnswer: "훈민정음 해례본",
    answerType: "phrase",
    maxInputChars: 160,
    thresholdScore: 86,
    teaserText: "문자 원리, 해설서, 세종의 맥락을 잘 엮으면 더 높은 점수를 받을 수 있어.",
    tone: "지식을 아는 척하지만, 역사적 문맥에 강한 프롬프트 앞에 약한 고양이 캐릭터",
  },
];

module.exports = {
  CATEGORY_SEEDS,
  DEFAULT_DAILY_WORD,
  SAMPLE_PROMPT_ROOMS,
};
